# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('units', models.IntegerField()),
                ('description', models.TextField()),
                ('purchase_date', models.DateTimeField()),
            ],
        ),
    ]
